import { RiddleData } from "../api/types";

export const OFFLINE_RIDDLES: RiddleData[] = [
  {
    id: 99201,
    riddleEn: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?",
    riddleNe: "मुख बिना बोल्छु, कान बिना सुन्छु। मेरो कुनै शरीर छैन तर बताससँगै म जीवित हुन्छु। म के हुँ?",
    answerEn: "An Echo",
    answerNe: "प्रतिध्वनि (Echo)",
    category: "nature",
    categoryEn: "Nature Riddle",
    categoryNe: "प्राकृतिक पहेली",
    meaningEn: "Sound reflections bouncing off surfaces create echoes without requiring a physical living body.",
    meaningNe: "ध्वनिको परावर्तनले कुनै भौतिक शरीर बिना नै आवाज फर्काउँछ।",
    difficulty: 2,
    date: new Date().toISOString().slice(0, 10),
    solved: false,
    xpEarned: 15,
  },
  {
    id: 99202,
    riddleEn: "What has keys, but no locks; space, but no room; and you can enter, but you cannot go outside?",
    riddleNe: "चाबीहरू छन् तर ताल्चा छैन, Space छ तर कोठा छैन, Enter गर्न सकिन्छ तर बाहिर जान सकिँदैन। के हो?",
    answerEn: "A Keyboard",
    answerNe: "किबोर्ड (Keyboard)",
    category: "tech",
    categoryEn: "Tech Riddle",
    categoryNe: "प्रविधि पहेली",
    meaningEn: "A computer keyboard consists of keys, a spacebar, and an enter key.",
    meaningNe: "कम्प्युटर किबोर्डमा चाबी (keys), स्पेस र इन्टर बटन हुन्छन्।",
    difficulty: 1,
    date: new Date().toISOString().slice(0, 10),
    solved: false,
    xpEarned: 15,
  },
  {
    id: 99203,
    riddleEn: "गाउँखाने कथा: माथिबाट खस्यो बाटुलो, भुइँमा झर्दा पाटुलो। के हो?",
    riddleNe: "माथिबाट खस्यो बाटुलो, भुइँमा झर्दा पाटुलो। के हो?",
    answerEn: "A Dry Tree Leaf",
    answerNe: "सुकेको रूखको पात",
    category: "folk",
    categoryEn: "Nepali Folk Riddle",
    categoryNe: "गाउँखाने कथा",
    meaningEn: "A dry leaf falls curling like a circle and flattens upon settling on the ground.",
    meaningNe: "रूखको सुकेको पात झर्दा गोलो र भुइँमा पुग्दा च्याप्टो बन्छ।",
    difficulty: 2,
    date: new Date().toISOString().slice(0, 10),
    solved: false,
    xpEarned: 15,
  },
  {
    id: 99204,
    riddleEn: "The more of this there is, the less you see. What is it?",
    riddleNe: "जति धेरै यो हुन्छ, त्यति नै कम तपाईं देख्नुहुन्छ। यो के हो?",
    answerEn: "Darkness",
    answerNe: "अँध्यारो (Darkness)",
    category: "logic",
    categoryEn: "Logic Riddle",
    categoryNe: "तार्किक पहेली",
    meaningEn: "Darkness absorbs visual light, diminishing vision as its intensity increases.",
    meaningNe: "अँध्यारो जति बढ्छ, उज्यालो र दृश्यता त्यति नै घट्दै जान्छ।",
    difficulty: 1,
    date: new Date().toISOString().slice(0, 10),
    solved: false,
    xpEarned: 15,
  },
  {
    id: 99205,
    riddleEn: "गाउँखाने कथा: चार भाइको एउटै टोपी। के हो?",
    riddleNe: "चार भाइको एउटै टोपी। के हो?",
    answerEn: "Clove (Lwang)",
    answerNe: "ल्वाङ",
    category: "folk",
    categoryEn: "Nepali Folk Riddle",
    categoryNe: "गाउँखाने कथा",
    meaningEn: "A clove spice flower bud appears with four prongs joined under one central head.",
    meaningNe: "ल्वाङको माथि चारवटा टुप्पा जोडिएर एउटा टोपी जस्तो स्वरूप बनेको हुन्छ।",
    difficulty: 2,
    date: new Date().toISOString().slice(0, 10),
    solved: false,
    xpEarned: 15,
  },
];

export function getOfflineRiddle(): RiddleData {
  const rnd = Math.floor(Math.random() * OFFLINE_RIDDLES.length);
  return OFFLINE_RIDDLES[rnd];
}
