import { Router } from "express";
import db from "../db.js";
import { requireAuth } from "../auth.js";
import {
  serializeUser,
  serializeDigest,
  optionOrder,
  originalChoiceIndex,
  studentQuestion,
  gradeBandFor,
  today,
  daysAgo,
  weekStart,
  levelForXp,
  friendCode,
  parseFriendCode,
} from "../util.js";
import { composeDailyQuiz, composeRevengeRound, composePracticeQuiz } from "../quizComposer.js";
import { checkAwards, awardsForUser } from "../awards.js";
import { isOnline } from "../presence.js";
import { sendPushToUser } from "../services/notifications.js";
import { autoGenerateDigestsForDate } from "../services/scheduler.js";

const BOT_PHONE = "9900000000";

function getBotUser() {
  return db.prepare("SELECT id FROM users WHERE phone = ?").get(BOT_PHONE);
}

/** One sample past battle so the Battle tab isn't empty for brand-new students. */
function ensureDemoBattle(userId) {
  const count = db
    .prepare("SELECT COUNT(*) c FROM battles WHERE p1 = ? OR p2 = ?")
    .get(userId, userId).c;
  if (count > 0) return;
  const bot = getBotUser();
  if (!bot || bot.id === userId) return;
  db.prepare("INSERT INTO battles (p1, p2, s1, s2, winner, date) VALUES (?, ?, ?, ?, ?, ?)").run(
    userId,
    bot.id,
    420,
    380,
    userId,
    daysAgo(2)
  );
}

function ensureDemoFriend(userId) {
  const bot = getBotUser();
  if (!bot || bot.id === userId) return;
  db.prepare("INSERT OR IGNORE INTO friendships (user_id, friend_id) VALUES (?, ?)").run(
    userId,
    bot.id
  );
  db.prepare("INSERT OR IGNORE INTO friendships (user_id, friend_id) VALUES (?, ?)").run(
    bot.id,
    userId
  );
}

const router = Router();
router.use(requireAuth);

const COUNTRIES = ["nepal", "india", "usa", "japan", "uk", "china", "australia", "global"];
const SUBJECTS = ["math", "science", "social", "english", "nepali", "gk", "current"];

// ---------- Profile ----------

router.get("/me", (req, res) => res.json({ user: serializeUser(req.user) }));

router.put("/me", (req, res) => {
  const b = req.body || {};
  const sets = [];
  const params = [];
  if (typeof b.name === "string") { sets.push("name = ?"); params.push(b.name.slice(0, 60)); }
  if (Number.isInteger(b.grade) && b.grade >= 1 && b.grade <= 12) { sets.push("grade = ?"); params.push(b.grade); }
  if (["en", "ne", "hi", "es", "fr", "de", "ja", "zh"].includes(b.language)) { sets.push("language = ?"); params.push(b.language); }
  if (COUNTRIES.includes(b.homeCountry)) { sets.push("home_country = ?"); params.push(b.homeCountry); }
  if (Array.isArray(b.extraCountries)) {
    const extras = b.extraCountries.filter((c) => COUNTRIES.includes(c)).slice(0, 2);
    sets.push("extra_countries = ?"); params.push(JSON.stringify(extras));
  }
  if (Array.isArray(b.subjects)) {
    sets.push("subjects = ?"); params.push(JSON.stringify(b.subjects.filter((s) => SUBJECTS.includes(s))));
  }
  // Accept both the app's "afterschool" and the legacy "afternoon" label.
  if (["morning", "afternoon", "afterschool", "evening"].includes(b.quizTime)) { sets.push("quiz_time = ?"); params.push(b.quizTime); }
  if (b.avatar && typeof b.avatar === "object") { sets.push("avatar = ?"); params.push(JSON.stringify(b.avatar)); }
  if (typeof b.joinCode === "string" && b.joinCode.trim()) {
    const school = db.prepare("SELECT id FROM schools WHERE join_code = ?").get(b.joinCode.trim().toUpperCase());
    if (school) { sets.push("school_id = ?"); params.push(school.id); }
  }
  const oldGrade = req.user.grade;
  const oldHomeCountry = req.user.home_country;
  const oldExtras = req.user.extra_countries;

  if (sets.length) {
    db.prepare(`UPDATE users SET ${sets.join(", ")} WHERE id = ?`).run(...params, req.user.id);
  }

  // If grade or country syllabus changed, immediately invalidate today's daily quiz
  // so the user gets fresh questions strictly tailored to their newly selected class & country!
  const gradeChanged = Number.isInteger(b.grade) && b.grade !== oldGrade;
  const countryChanged = b.homeCountry && b.homeCountry !== oldHomeCountry;
  const extrasChanged = Array.isArray(b.extraCountries) && JSON.stringify(b.extraCountries) !== oldExtras;
  if (gradeChanged || countryChanged || extrasChanged) {
    db.prepare("DELETE FROM quizzes WHERE user_id = ? AND date = ? AND kind = 'daily'").run(req.user.id, today());
  }

  const user = db.prepare("SELECT * FROM users WHERE id = ?").get(req.user.id);
  res.json({ user: serializeUser(user) });
});

function handlePushTokenRegistration(req, res) {
  const token = req.body?.token;
  if (typeof token === "string" && token.trim()) {
    const cleanToken = token.trim();
    db.prepare("INSERT OR REPLACE INTO push_tokens (user_id, token) VALUES (?, ?)").run(req.user.id, cleanToken);
    console.log(`[Push] Registered token for user ${req.user.id} (${cleanToken.slice(0, 25)}...)`);
  }
  res.json({ ok: true });
}

router.post("/me/push-token", handlePushTokenRegistration);
router.post("/push-token", handlePushTokenRegistration);

// Join a school (or class) by its code so class/school ranks light up.
router.post("/school/join", (req, res) => {
  const code = String(req.body.joinCode || "").trim().toUpperCase();
  if (!code) return res.status(400).json({ error: "Enter your school code" });
  const school = db.prepare("SELECT * FROM schools WHERE join_code = ?").get(code);
  if (!school) return res.status(404).json({ error: "No school found with that code" });
  db.prepare("UPDATE users SET school_id = ? WHERE id = ?").run(school.id, req.user.id);
  const user = db.prepare("SELECT * FROM users WHERE id = ?").get(req.user.id);
  res.json({ user: serializeUser(user), school: { id: school.id, name: school.name } });
});

// Leave the current school.
router.post("/school/leave", (req, res) => {
  db.prepare("UPDATE users SET school_id = NULL WHERE id = ?").run(req.user.id);
  const user = db.prepare("SELECT * FROM users WHERE id = ?").get(req.user.id);
  res.json({ user: serializeUser(user) });
});

// Create a new school clan
router.post("/school/create", (req, res) => {
  const name = String(req.body.name || "").trim().slice(0, 60);
  const district = String(req.body.district || "Kathmandu").trim().slice(0, 40);
  if (name.length < 2) {
    return res.status(400).json({ error: "School name must be at least 2 characters" });
  }

  // Generate clean 6-character code (e.g., SX-482 or KMC-719)
  const letters = name.replace(/[^A-Za-z]/g, "").toUpperCase();
  const prefix = (letters.length >= 3 ? letters.slice(0, 3) : (letters + "QQ").slice(0, 3));
  const randNum = Math.floor(100 + Math.random() * 900);
  let joinCode = `${prefix}-${randNum}`;

  const existing = db.prepare("SELECT id FROM schools WHERE join_code = ?").get(joinCode);
  if (existing) {
    joinCode = `${prefix}-${Math.floor(1000 + Math.random() * 9000)}`;
  }

  const info = db.prepare(`
    INSERT INTO schools (name, district, join_code, creator_user_id)
    VALUES (?, ?, ?, ?)
  `).run(name, district, joinCode, req.user.id);

  const schoolId = info.lastInsertRowid;
  db.prepare("UPDATE users SET school_id = ? WHERE id = ?").run(schoolId, req.user.id);

  const user = db.prepare("SELECT * FROM users WHERE id = ?").get(req.user.id);
  res.json({
    user: serializeUser(user),
    school: {
      id: schoolId,
      name,
      district,
      joinCode,
      membersCount: 1,
      totalXp: user.xp,
    },
  });
});

// Get user's current school clan details and top members
router.get("/school/my", (req, res) => {
  if (!req.user.school_id) {
    return res.json({ school: null });
  }
  const school = db.prepare("SELECT * FROM schools WHERE id = ?").get(req.user.school_id);
  if (!school) {
    return res.json({ school: null });
  }

  const members = db.prepare(`
    SELECT id, name, avatar, grade, xp, streak
    FROM users
    WHERE school_id = ?
    ORDER BY xp DESC
    LIMIT 50
  `).all(school.id);

  const totalXp = members.reduce((sum, m) => sum + (m.xp || 0), 0);

  res.json({
    school: {
      id: school.id,
      name: school.name,
      district: school.district || "Kathmandu",
      joinCode: school.join_code,
      verified: Boolean(school.verified),
      badge: school.badge || "🏫",
      membersCount: members.length,
      totalXp,
      members: members.map((m) => ({
        id: m.id,
        name: m.name || "Player",
        avatar: JSON.parse(m.avatar || "{}"),
        grade: m.grade,
        xp: m.xp,
        streak: m.streak,
        isMe: m.id === req.user.id,
      })),
    },
  });
});

// Top schools national leaderboard
router.get("/school/leaderboard", (req, res) => {
  const schools = db.prepare(`
    SELECT s.id, s.name, s.district, s.join_code as joinCode, s.badge, s.verified,
           COUNT(u.id) as membersCount,
           COALESCE(SUM(u.xp), 0) as totalXp
    FROM schools s
    LEFT JOIN users u ON u.school_id = s.id
    GROUP BY s.id
    HAVING membersCount > 0
    ORDER BY totalXp DESC
    LIMIT 20
  `).all();

  res.json({
    schools: schools.map((s, idx) => ({
      ...s,
      rank: idx + 1,
      verified: Boolean(s.verified),
    })),
  });
});

// ---------- Memory Block Quiz Game ----------

router.get("/memory/packs", (req, res) => {
  const { subject, limit = 30, offset = 0, random } = req.query;
  let query = "SELECT * FROM memory_packs";
  const params = [];
  if (subject) {
    query += " WHERE subject = ?";
    params.push(subject);
  }
  // Default to random order for variety; explicit order=asc for pagination
  const useRandom = random !== "0" && req.query.order !== "asc";
  if (useRandom) {
    query += " ORDER BY RANDOM() LIMIT ?";
    params.push(Math.min(Number(limit) || 30, 120));
  } else {
    query += " ORDER BY id ASC LIMIT ? OFFSET ?";
    params.push(Math.min(Number(limit) || 30, 120));
    params.push(Number(offset) || 0);
  }
  const rows = db.prepare(query).all(...params);
  const totalCount = db.prepare("SELECT COUNT(*) as c FROM memory_packs").get().c;
  const packs = rows.map((r) => ({
    id: r.id,
    titleEn: r.title_en,
    titleNe: r.title_ne,
    subject: r.subject,
    difficulty: r.difficulty,
    timeLimitSec: r.time_limit_sec,
    pairs: JSON.parse(r.pairs || "[]"),
  }));
  res.json({ packs, totalCount });
});

router.get("/memory/packs/random", (req, res) => {
  const { subject } = req.query;
  let query = "SELECT * FROM memory_packs";
  const params = [];
  if (subject) {
    query += " WHERE subject = ?";
    params.push(subject);
  }
  query += " ORDER BY RANDOM() LIMIT 1";
  const row = db.prepare(query).get(...params);
  if (!row) {
    return res.status(404).json({ error: "No packs found" });
  }
  res.json({
    pack: {
      id: row.id,
      titleEn: row.title_en,
      titleNe: row.title_ne,
      subject: row.subject,
      difficulty: row.difficulty,
      timeLimitSec: row.time_limit_sec,
      pairs: JSON.parse(row.pairs || "[]"),
    },
  });
});

router.post("/memory/submit", (req, res) => {
  const { packId, moves, timeMs } = req.body || {};
  if (!packId || typeof moves !== "number" || typeof timeMs !== "number") {
    return res.status(400).json({ error: "Invalid payload" });
  }

  let stars = 1;
  if (moves <= 10) stars = 3;
  else if (moves <= 14) stars = 2;

  const xpEarned = 30 + stars * 10;

  db.prepare(`
    INSERT INTO memory_scores (user_id, pack_id, moves, time_ms, stars, xp_earned)
    VALUES (?, ?, ?, ?, ?, ?)
  `).run(req.user.id, packId, moves, timeMs, stars, xpEarned);

  db.prepare("UPDATE users SET xp = xp + ? WHERE id = ?").run(xpEarned, req.user.id);
  db.prepare("INSERT INTO xp_events (user_id, amount, reason, date) VALUES (?, ?, 'memory_game', ?)")
    .run(req.user.id, xpEarned, today());

  const freshUser = db.prepare("SELECT * FROM users WHERE id = ?").get(req.user.id);

  res.json({
    stars,
    moves,
    timeMs,
    xpEarned,
    user: serializeUser(freshUser),
  });
});

// ---------- Question Reporting ----------

router.post("/question/report", (req, res) => {
  const { questionId, reason, details } = req.body || {};
  if (!questionId || !reason) {
    return res.status(400).json({ error: "questionId and reason are required" });
  }
  db.prepare(`
    INSERT INTO reported_questions (user_id, question_id, reason, details)
    VALUES (?, ?, ?, ?)
  `).run(req.user.id, questionId, String(reason).slice(0, 50), String(details || "").slice(0, 300));

  res.json({ ok: true, message: "Report submitted. Thank you for keeping QuizQuest accurate!" });
});

// ---------- Daily Zip Challenge & Social Nudge ----------

function getDailyZipSpecs(dateStr) {
  const d = new Date(dateStr + "T00:00:00Z");
  const epoch = new Date("2026-01-01T00:00:00Z");
  const dayNum = Math.max(1, Math.floor((d.getTime() - epoch.getTime()) / 86400000) + 1);
  const dayOfWeek = d.getUTCDay();

  // Day-of-week Level-Up Progression:
  // Mon/Wed: 5x5 (Level 1: 7 checkpoints, 4 walls)
  // Tue/Thu/Fri: 6x6 (Level 2: 9 checkpoints, 7 walls)
  // Sun: 7x7 (Level 3: 12 checkpoints, 10 walls)
  // Sat (Weekend Grand Challenge): 8x8 (Master Level: 14 checkpoints, 12 walls)
  const size = dayOfWeek === 6 ? 8 : dayOfWeek === 0 ? 7 : [1, 3].includes(dayOfWeek) ? 5 : 6;
  const difficulty = size === 8 ? "hard" : size === 7 ? "hard" : size === 6 ? "medium" : "easy";

  let seed = (dayNum * 2654435761) >>> 0;
  const rng = () => {
    seed = (seed ^ (seed << 13)) >>> 0;
    seed = (seed ^ (seed >> 17)) >>> 0;
    seed = (seed ^ (seed << 5)) >>> 0;
    return (seed >>> 0) / 4294967296;
  };

  const total = size * size;
  const visited = Array.from({ length: size }, () => Array(size).fill(false));

  const neighbors = (r, c) => {
    const list = [];
    const deltas = [[-1, 0], [1, 0], [0, -1], [0, 1]];
    for (const [dr, dc] of deltas) {
      const nr = r + dr;
      const nc = c + dc;
      if (nr >= 0 && nr < size && nc >= 0 && nc < size && !visited[nr][nc]) {
        list.push({ row: nr, col: nc });
      }
    }
    return list;
  };

  const path = [];
  let backtrackSteps = 0;
  const MAX_BACKTRACK_STEPS = 2500;

  function backtrack(r, c) {
    if (++backtrackSteps > MAX_BACKTRACK_STEPS) return false;
    visited[r][c] = true;
    path.push({ row: r, col: c });
    if (path.length === total) return true;

    const nbrs = neighbors(r, c);
    for (const n of nbrs) {
      if (neighbors(n.row, n.col).length === 0 && path.length < total - 1) {
        visited[r][c] = false;
        path.pop();
        return false;
      }
    }

    nbrs.sort((a, b) => {
      const degA = neighbors(a.row, a.col).length;
      const degB = neighbors(b.row, b.col).length;
      if (degA !== degB) return degA - degB;
      return rng() - 0.5;
    });

    for (const n of nbrs) {
      if (backtrack(n.row, n.col)) return true;
    }
    visited[r][c] = false;
    path.pop();
    return false;
  }

  const corners = [
    { row: 0, col: 0 },
    { row: 0, col: size - 1 },
    { row: size - 1, col: 0 },
    { row: size - 1, col: size - 1 },
    { row: Math.floor(size / 2), col: 0 },
    { row: 0, col: Math.floor(size / 2) },
    { row: Math.floor(size / 2), col: size - 1 },
    { row: size - 1, col: Math.floor(size / 2) },
  ];
  const shuffledCorners = [...corners].sort(() => rng() - 0.5);
  let pathFound = false;
  for (const st of shuffledCorners) {
    backtrackSteps = 0;
    for (let r = 0; r < size; r++) visited[r].fill(false);
    path.length = 0;
    if (backtrack(st.row, st.col)) {
      pathFound = true;
      break;
    }
  }

  if (!pathFound) {
    path.length = 0;
    for (let r = 0; r < size; r++) {
      if (r % 2 === 0) {
        for (let c = 0; c < size; c++) path.push({ row: r, col: c });
      } else {
        for (let c = size - 1; c >= 0; c--) path.push({ row: r, col: c });
      }
    }
  }

  // Checkpoints: authentic LinkedIn number dilemma
  const targetCheckpoints = size === 5 ? 7 : size === 6 ? 9 : size === 7 ? 11 : 13;
  const numCheckpoints = Math.min(total, targetCheckpoints);

  const selectedIndices = [0];
  const innerCount = numCheckpoints - 2;
  if (innerCount > 0) {
    const idealStep = (total - 1) / (numCheckpoints - 1);
    for (let i = 1; i <= innerCount; i++) {
      const idealIdx = Math.round(i * idealStep);
      const jitter = Math.floor(rng() * 3) - 1;
      const minAllowed = selectedIndices[selectedIndices.length - 1] + 1;
      const maxAllowed = total - 1 - (innerCount - i + 1);
      const chosenIdx = Math.max(minAllowed, Math.min(maxAllowed, idealIdx + jitter));
      selectedIndices.push(chosenIdx);
    }
  }
  selectedIndices.push(total - 1);

  const checkpoints = {};
  const numbers = {};
  selectedIndices.forEach((idx, cpIdx) => {
    const cell = path[idx];
    const num = cpIdx + 1;
    checkpoints[`${cell.row}-${cell.col}`] = num;
    numbers[`${cell.row},${cell.col}`] = num;
  });
  const cpNum = selectedIndices.length;

  // Strategic connected obstacle walls (L-shapes, U-shapes, and corridor dividers)
  const targetWalls = size <= 5 ? 3 : size <= 6 ? 5 : size <= 7 ? 7 : 9;
  const walls = [];
  const wallsSet = new Set();
  const pathIndexMap = new Map();
  path.forEach((p, idx) => pathIndexMap.set(`${p.row},${p.col}`, idx));

  // Count walls surrounding each cell so no cell becomes enclosed
  const cellWallCount = new Map();
  const getWallCount = (r, c) => cellWallCount.get(`${r},${c}`) || 0;
  const incWallCount = (r, c) => cellWallCount.set(`${r},${c}`, getWallCount(r, c) + 1);

  const canPlaceWall = (rA, cA, rB, cB) => {
    const keyA = `${rA},${cA}`;
    const keyB = `${rB},${cB}`;
    const idxA = pathIndexMap.get(keyA);
    const idxB = pathIndexMap.get(keyB);
    if (idxA === undefined || idxB === undefined) return false;
    // Wall can NEVER cross consecutive steps in the solution path
    if (Math.abs(idxA - idxB) <= 1) return false;
    const wKey = keyA < keyB ? `${keyA}|${keyB}` : `${keyB}|${keyA}`;
    if (wallsSet.has(wKey)) return false;
    // Prevent blocking any cell completely (need at least 2 open exits)
    if (getWallCount(rA, cA) >= 2 || getWallCount(rB, cB) >= 2) return false;
    return true;
  };

  const addWall = (rA, cA, rB, cB) => {
    const keyA = `${rA},${cA}`;
    const keyB = `${rB},${cB}`;
    const wKey = keyA < keyB ? `${keyA}|${keyB}` : `${keyB}|${keyA}`;
    wallsSet.add(wKey);
    walls.push({ between: [keyA, keyB] });
    incWallCount(rA, cA);
    incWallCount(rB, cB);
  };

  // Grow walls into continuous multi-segment corridors / L-shapes
  for (let i = 0; i < path.length && walls.length < targetWalls; i++) {
    const p = path[i];
    const deltas = [[1, 0], [0, 1]];
    for (const [dr, dc] of deltas) {
      if (walls.length >= targetWalls) break;
      const nr = p.row + dr;
      const nc = p.col + dc;
      if (nr < size && nc < size && canPlaceWall(p.row, p.col, nr, nc)) {
        addWall(p.row, p.col, nr, nc);

        // Try chaining an extension (creating an L-corner or 2-3 segment run)
        const extensions = [
          // Continuation along same line
          dr !== 0 ? [p.row + dr, p.col, p.row + 2 * dr, p.col] : [p.row, p.col + dc, p.row, p.col + 2 * dc],
          // L-corner turn
          dr !== 0 ? [p.row, p.col, p.row, p.col + 1] : [p.row, p.col, p.row + 1, p.col],
          dr !== 0 ? [p.row, p.col, p.row, p.col - 1] : [p.row, p.col, p.row - 1, p.col],
        ];

        for (const [erA, ecA, erB, ecB] of extensions) {
          if (walls.length >= targetWalls) break;
          if (
            erA >= 0 && erA < size && ecA >= 0 && ecA < size &&
            erB >= 0 && erB < size && ecB >= 0 && ecB < size &&
            canPlaceWall(erA, ecA, erB, ecB)
          ) {
            addWall(erA, ecA, erB, ecB);
            break;
          }
        }
      }
    }
  }

  return {
    puzzleNum: dayNum,
    date: dateStr,
    size: { rows: size, cols: size },
    difficulty,
    totalCells: total,
    numbers,
    walls,
    solution: path.map((p) => `${p.row},${p.col}`),
    checkpoints,
    maxCheckpoint: cpNum,
    solutionPath: path,
  };
}

router.get("/zip/daily", (req, res) => {
  const dateStr = req.query.date || today();
  const specs = getDailyZipSpecs(dateStr);

  // Check if player has already submitted for today
  const myScoreRow = db
    .prepare("SELECT * FROM daily_zip_scores WHERE user_id = ? AND puzzle_date = ?")
    .get(req.user.id, dateStr);

  const myScore = myScoreRow
    ? {
        timeSeconds: myScoreRow.time_seconds,
        moves: myScoreRow.moves,
        stars: myScoreRow.stars,
        xpEarned: myScoreRow.xp_earned,
        completedAt: myScoreRow.created_at,
      }
    : null;

  // Fastest friend rival to beat
  const rivalRow = db
    .prepare(`
      SELECT u.id, u.name, u.avatar, s.time_seconds
      FROM daily_zip_scores s
      JOIN users u ON s.user_id = u.id
      JOIN friendships f ON (f.friend_id = s.user_id AND f.user_id = ?)
      WHERE s.puzzle_date = ?
      ORDER BY s.time_seconds ASC
      LIMIT 1
    `)
    .get(req.user.id, dateStr);

  const rivalToBeat = rivalRow
    ? {
        userId: rivalRow.id,
        name: rivalRow.name || "Friend",
        avatar: JSON.parse(rivalRow.avatar || "{}"),
        timeSeconds: rivalRow.time_seconds,
      }
    : null;

  res.json({
    ...specs,
    myScore,
    rivalToBeat,
  });
});

router.post(["/zip/daily/submit", "/games/zip/daily/score"], (req, res) => {
  const { puzzleDate, timeSeconds, moves, stars = 3 } = req.body || {};
  const dateStr = puzzleDate || today();

  if (typeof timeSeconds !== "number" || typeof moves !== "number") {
    return res.status(400).json({ error: "Invalid score payload" });
  }

  const specs = getDailyZipSpecs(dateStr);
  const xpEarned = 40 + Math.min(3, Math.max(1, stars)) * 10;

  // Keep first official daily score
  const existing = db
    .prepare("SELECT * FROM daily_zip_scores WHERE user_id = ? AND puzzle_date = ?")
    .get(req.user.id, dateStr);

  if (!existing) {
    db.prepare(`
      INSERT INTO daily_zip_scores (user_id, puzzle_date, puzzle_num, size, time_seconds, moves, stars, xp_earned)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `).run(req.user.id, dateStr, specs.puzzleNum, specs.size, timeSeconds, moves, stars, xpEarned);

    db.prepare("UPDATE users SET xp = xp + ? WHERE id = ?").run(xpEarned, req.user.id);
    db.prepare("INSERT INTO xp_events (user_id, amount, reason, date) VALUES (?, ?, 'daily_zip', ?)")
      .run(req.user.id, xpEarned, today());
  }

  const freshUser = db.prepare("SELECT * FROM users WHERE id = ?").get(req.user.id);

  res.json({
    ok: true,
    score: {
      puzzleDate: dateStr,
      timeSeconds,
      moves,
      stars,
      xpEarned: existing ? 0 : xpEarned,
      isNewRecord: !existing,
    },
    user: serializeUser(freshUser),
  });
});

router.get("/zip/daily/leaderboard", (req, res) => {
  const dateStr = req.query.date || today();
  const userId = req.user.id;

  // 1. Global top 15 solvers
  const globalRows = db
    .prepare(`
      SELECT u.id, u.name, u.avatar, u.xp, s.time_seconds, s.moves, s.stars, s.created_at
      FROM daily_zip_scores s
      JOIN users u ON s.user_id = u.id
      WHERE s.puzzle_date = ?
      ORDER BY s.time_seconds ASC, s.moves ASC
      LIMIT 15
    `)
    .all(dateStr);

  const global = globalRows.map((r, i) => ({
    rank: i + 1,
    userId: r.id,
    name: r.name || "Player",
    avatar: JSON.parse(r.avatar || "{}"),
    level: levelForXp(r.xp),
    timeSeconds: r.time_seconds,
    moves: r.moves,
    stars: r.stars,
    isMe: r.id === userId,
  }));

  // 2. Friends who completed today
  const friendsRows = db
    .prepare(`
      SELECT u.id, u.name, u.avatar, u.xp, s.time_seconds, s.moves, s.stars, s.created_at
      FROM daily_zip_scores s
      JOIN users u ON s.user_id = u.id
      WHERE s.puzzle_date = ? AND (u.id = ? OR u.id IN (SELECT friend_id FROM friendships WHERE user_id = ?))
      ORDER BY s.time_seconds ASC, s.moves ASC
    `)
    .all(dateStr, userId, userId);

  const friends = friendsRows.map((r, i) => ({
    rank: i + 1,
    userId: r.id,
    name: r.name || "Friend",
    avatar: JSON.parse(r.avatar || "{}"),
    level: levelForXp(r.xp),
    timeSeconds: r.time_seconds,
    moves: r.moves,
    stars: r.stars,
    isMe: r.id === userId,
  }));

  // 3. Friends who have NOT played yet (nudgeable)
  const unplayedRows = db
    .prepare(`
      SELECT u.id, u.name, u.avatar
      FROM friendships f
      JOIN users u ON f.friend_id = u.id
      WHERE f.user_id = ? AND u.id NOT IN (SELECT user_id FROM daily_zip_scores WHERE puzzle_date = ?)
    `)
    .all(userId, dateStr);

  const nudgedIds = new Set(
    db
      .prepare("SELECT to_user_id FROM zip_nudges WHERE from_user_id = ? AND puzzle_date = ?")
      .all(userId, dateStr)
      .map((r) => r.to_user_id)
  );

  const unplayedFriends = unplayedRows.map((u) => ({
    userId: u.id,
    name: u.name || "Friend",
    avatar: JSON.parse(u.avatar || "{}"),
    canNudge: !nudgedIds.has(u.id),
  }));

  // 4. School clan members
  let school = [];
  if (req.user.school_id) {
    const schoolRows = db
      .prepare(`
        SELECT u.id, u.name, u.avatar, u.xp, s.time_seconds, s.moves, s.stars
        FROM daily_zip_scores s
        JOIN users u ON s.user_id = u.id
        WHERE s.puzzle_date = ? AND u.school_id = ?
        ORDER BY s.time_seconds ASC, s.moves ASC
        LIMIT 20
      `)
      .all(dateStr, req.user.school_id);

    school = schoolRows.map((r, i) => ({
      rank: i + 1,
      userId: r.id,
      name: r.name || "Schoolmate",
      avatar: JSON.parse(r.avatar || "{}"),
      level: levelForXp(r.xp),
      timeSeconds: r.time_seconds,
      moves: r.moves,
      stars: r.stars,
      isMe: r.id === userId,
    }));
  }

  res.json({ global, friends, unplayedFriends, school });
});

router.post("/zip/daily/nudge", async (req, res) => {
  const { targetUserId, puzzleDate } = req.body || {};
  const dateStr = puzzleDate || today();

  if (!targetUserId || targetUserId === req.user.id) {
    return res.status(400).json({ error: "Invalid target user" });
  }

  // Check rate limit: 1 nudge per friend per day
  const existing = db
    .prepare("SELECT id FROM zip_nudges WHERE from_user_id = ? AND to_user_id = ? AND puzzle_date = ?")
    .get(req.user.id, targetUserId, dateStr);

  if (existing) {
    return res.status(429).json({ error: "You already nudged this friend today. Give them time to play!" });
  }

  db.prepare(`
    INSERT INTO zip_nudges (from_user_id, to_user_id, puzzle_date)
    VALUES (?, ?, ?)
  `).run(req.user.id, targetUserId, dateStr);

  // Send push notification asynchronously
  const senderName = req.user.name || "A friend";
  sendPushToUser({
    userId: targetUserId,
    title: `⚡ Daily Zip Challenge from ${senderName}!`,
    body: `${senderName} completed today's Daily Zip! Think you can beat their time? Tap to play!`,
    data: {
      type: "zip_nudge",
      fromUserId: req.user.id,
      puzzleDate: dateStr,
    },
  }).catch(() => {});

  res.json({ ok: true, message: `Nudge sent to friend! ⚡` });
});

// ---------- Home & digest ----------

function publishedDigest(gradeBand) {
  const todayStr = today();
  let row = db
    .prepare("SELECT * FROM digests WHERE date = ? AND grade_band = ? AND status = 'published' ORDER BY id DESC")
    .get(todayStr, gradeBand);

  if (!row) {
    try {
      autoGenerateDigestsForDate(todayStr);
      row = db
        .prepare("SELECT * FROM digests WHERE date = ? AND grade_band = ? AND status = 'published' ORDER BY id DESC")
        .get(todayStr, gradeBand);
    } catch (err) {
      console.error("[Student] Auto-generate digest fallback error:", err);
    }
  }

  // Fallback 1: Any published digest for today
  if (!row) {
    row = db
      .prepare("SELECT * FROM digests WHERE date = ? AND status = 'published' ORDER BY id DESC")
      .get(todayStr);
  }

  // Fallback 2: Most recent published digest in the system
  if (!row) {
    row = db
      .prepare("SELECT * FROM digests WHERE status = 'published' ORDER BY date DESC, id DESC")
      .get();
  }

  return row;
}

function getDailyRiddle(userId) {
  const todayStr = today();
  const parts = todayStr.split("-").map(Number);
  const dayHash = (parts[0] || 2026) * 365 + (parts[1] || 1) * 31 + (parts[2] || 1);

  const totalRiddles = db.prepare("SELECT COUNT(*) c FROM riddles WHERE status = 'approved'").get()?.c || 0;
  if (totalRiddles === 0) return null;

  const offset = dayHash % totalRiddles;
  const riddle = db.prepare("SELECT * FROM riddles WHERE status = 'approved' ORDER BY id ASC LIMIT 1 OFFSET ?").get(offset);
  if (!riddle) return null;

  const solved = db.prepare("SELECT * FROM user_riddle_solves WHERE user_id = ? AND date = ?").get(userId, todayStr);

  return {
    id: riddle.id,
    riddleEn: riddle.riddle_en,
    riddleNe: riddle.riddle_ne,
    answerEn: riddle.answer_en,
    answerNe: riddle.answer_ne,
    hint1En: riddle.hint1_en,
    hint1Ne: riddle.hint1_ne,
    hint2En: riddle.hint2_en,
    hint2Ne: riddle.hint2_ne,
    hint3En: riddle.hint3_en,
    hint3Ne: riddle.hint3_ne,
    category: riddle.category,
    difficulty: riddle.difficulty,
    date: todayStr,
    solved: !!solved,
    xpEarned: solved ? solved.xp_earned : 15,
  };
}

router.get("/home", (req, res) => {
  const user = req.user;
  const gradeBand = gradeBandFor(user.grade || 8);
  const quiz = db
    .prepare("SELECT * FROM quizzes WHERE user_id = ? AND date = ? AND kind = 'daily'")
    .get(user.id, today());
  const dailyQuiz = {
    status: !quiz ? "not_started" : quiz.completed ? "completed" : "in_progress",
    score: quiz ? quiz.score : 0,
    total: quiz ? JSON.parse(quiz.question_ids).length : 8,
  };
  const weeklyXp =
    db.prepare("SELECT COALESCE(SUM(amount),0) s FROM xp_events WHERE user_id = ? AND date >= ?")
      .get(user.id, weekStart()).s;
  const recent = db
    .prepare("SELECT award_code, earned_at FROM user_awards WHERE user_id = ? ORDER BY earned_at DESC LIMIT 3")
    .all(user.id);
  const all = awardsForUser(user.id).filter((a) => a.earned);
  const recentAwards = recent
    .map((r) => all.find((a) => a.code === r.award_code))
    .filter(Boolean)
    .map(({ earned, ...a }) => a);

  const revengeQuiz = db
    .prepare("SELECT * FROM quizzes WHERE user_id = ? AND date = ? AND kind = 'revenge'")
    .get(user.id, today());
  const revengeAvail = (!revengeQuiz || !revengeQuiz.completed) && composeRevengeRound(user).length > 0;

  res.json({
    user: serializeUser(user),
    dailyQuiz,
    digest: serializeDigest(publishedDigest(gradeBand)),
    riddle: getDailyRiddle(user.id),
    revengeAvailable: revengeAvail,
    recentAwards,
    weeklyXp,
  });
});

router.get("/digest/today", (req, res) => {
  res.json({ digest: serializeDigest(publishedDigest(gradeBandFor(req.user.grade || 8))) });
});

router.get("/digest/random", (req, res) => {
  const row = db
    .prepare("SELECT * FROM digests WHERE status = 'published' ORDER BY RANDOM() LIMIT 1")
    .get();
  res.json({ digest: serializeDigest(row || publishedDigest(gradeBandFor(req.user.grade || 8))) });
});

router.get("/riddle/today", (req, res) => {
  res.json({ riddle: getDailyRiddle(req.user.id) });
});

router.get("/riddle/random", (req, res) => {
  const todayStr = today();
  const riddle = db.prepare("SELECT * FROM riddles WHERE status = 'approved' ORDER BY RANDOM() LIMIT 1").get();
  if (!riddle) return res.json({ riddle: null });

  const solved = db.prepare("SELECT * FROM user_riddle_solves WHERE user_id = ? AND riddle_id = ?").get(req.user.id, riddle.id);
  res.json({
    riddle: {
      id: riddle.id,
      riddleEn: riddle.riddle_en,
      riddleNe: riddle.riddle_ne,
      answerEn: riddle.answer_en,
      answerNe: riddle.answer_ne,
      hint1En: riddle.hint1_en,
      hint1Ne: riddle.hint1_ne,
      hint2En: riddle.hint2_en,
      hint2Ne: riddle.hint2_ne,
      hint3En: riddle.hint3_en,
      hint3Ne: riddle.hint3_ne,
      category: riddle.category,
      difficulty: riddle.difficulty,
      solved: Boolean(solved),
      date: todayStr,
    }
  });
});

router.post("/riddle/solve", (req, res) => {
  const userId = req.user.id;
  const todayStr = today();
  const { riddleId } = req.body || {};

  const existing = db.prepare("SELECT * FROM user_riddle_solves WHERE user_id = ? AND date = ?").get(userId, todayStr);
  if (existing) {
    return res.json({ success: true, alreadySolved: true, xpEarned: existing.xp_earned });
  }

  const xpReward = 15;
  try {
    db.prepare("INSERT INTO user_riddle_solves (user_id, riddle_id, date, xp_earned) VALUES (?, ?, ?, ?)").run(userId, riddleId || 1, todayStr, xpReward);
    db.prepare("INSERT INTO xp_events (user_id, amount, reason, date) VALUES (?, ?, 'daily_riddle', ?)").run(userId, xpReward, todayStr);
    db.prepare("UPDATE users SET xp = xp + ? WHERE id = ?").run(xpReward, userId);
  } catch (err) {
    console.error("riddle solve record error:", err);
  }

  const updatedUser = db.prepare("SELECT * FROM users WHERE id = ?").get(userId);

  res.json({
    success: true,
    alreadySolved: false,
    xpEarned: xpReward,
    totalXp: updatedUser.xp,
  });
});

// ---------- Quizzes ----------

function getOrCreateQuiz(user, kind) {
  let quiz = db
    .prepare("SELECT * FROM quizzes WHERE user_id = ? AND date = ? AND kind = ?")
    .get(user.id, today(), kind);

  // If daily quiz already exists, verify that its questions actually match the student's current grade band!
  if (quiz && kind === "daily") {
    const targetBand = gradeBandFor(user.grade || 8);
    const ids = JSON.parse(quiz.question_ids || "[]");
    if (ids.length) {
      const ph = ids.map(() => "?").join(",");
      const qRows = db.prepare(`SELECT grade_band FROM questions WHERE id IN (${ph})`).all(...ids);
      const wrongBand = qRows.some((q) => q.grade_band !== targetBand);
      if (wrongBand) {
        db.prepare("DELETE FROM quizzes WHERE id = ?").run(quiz.id);
        quiz = null;
      }
    }
  }

  if (!quiz) {
    const questions = kind === "daily" ? composeDailyQuiz(user) : composeRevengeRound(user);
    if (!questions.length) return null;
    const info = db
      .prepare("INSERT INTO quizzes (user_id, date, kind, question_ids) VALUES (?, ?, ?, ?)")
      .run(user.id, today(), kind, JSON.stringify(questions.map((q) => q.id)));
    quiz = db.prepare("SELECT * FROM quizzes WHERE id = ?").get(info.lastInsertRowid);
  }
  return quiz;
}

function questionsForQuiz(quiz, language) {
  const ids = JSON.parse(quiz.question_ids);
  const ph = ids.map(() => "?").join(",");
  const rows = db.prepare(`SELECT * FROM questions WHERE id IN (${ph})`).all(...ids);
  const byId = Object.fromEntries(rows.map((r) => [r.id, r]));
  return ids.map((id) => byId[id]).filter(Boolean).map((q) => studentQuestion(q, language, quiz.id));
}

router.get("/quiz/daily", (req, res) => {
  const quiz = getOrCreateQuiz(req.user, "daily");
  if (!quiz) return res.status(503).json({ error: "No questions available yet — check back soon!" });
  res.json({
    quizId: quiz.id,
    date: quiz.date,
    questions: questionsForQuiz(quiz, req.user.language),
    completed: Boolean(quiz.completed),
    score: quiz.score,
  });
});

router.get("/quiz/practice", (req, res) => {
  const user = req.user;
  const { subject } = req.query;
  const questions = composePracticeQuiz(user, subject || null);
  if (!questions || !questions.length) {
    return res.status(503).json({ error: "No practice questions available right now" });
  }

  // Create a practice quiz session in DB
  const info = db
    .prepare("INSERT INTO quizzes (user_id, date, kind, question_ids) VALUES (?, ?, 'practice', ?)")
    .run(user.id, today(), JSON.stringify(questions.map((q) => q.id)));

  const quiz = db.prepare("SELECT * FROM quizzes WHERE id = ?").get(info.lastInsertRowid);
  res.json({
    quizId: quiz.id,
    date: quiz.date,
    questions: questionsForQuiz(quiz, user.language),
    completed: false,
    score: 0,
  });
});

router.get("/quiz/revenge", (req, res) => {
  const existing = db
    .prepare("SELECT * FROM quizzes WHERE user_id = ? AND date = ? AND kind = 'revenge'")
    .get(req.user.id, today());
  if (existing && existing.completed) return res.status(404).json({ error: "Revenge round already done today" });
  const quiz = getOrCreateQuiz(req.user, "revenge");
  if (!quiz) return res.status(404).json({ error: "Nothing to avenge right now — nice work!" });
  res.json({ quizId: quiz.id, questions: questionsForQuiz(quiz, req.user.language) });
});

function submitQuiz(req, res, kind) {
  const user = req.user;
  const { quizId, answers } = req.body || {};

  // Offline quest sync support: Handle client-evaluated offline quests with anti-cheat caps
  const isOfflineSubmission = quizId === 999999 || req.body?.offlineTimestamp != null || req.body?.offlineScore != null;
  if (isOfflineSubmission) {
    const rawScore = Number(req.body?.offlineScore);
    const offlineScore = Math.max(0, Math.min(10, isNaN(rawScore) ? (Array.isArray(answers) ? answers.length : 0) : rawScore));
    const total = 10;
    const xpPerQ = kind === "daily" ? 10 : 8;
    const xpEarned = Math.min(150, offlineScore * xpPerQ);

    let streak = user.streak;
    let comeback = false;
    if (kind === "daily") {
      const last = user.last_quiz_date;
      if (last === daysAgo(1)) streak = user.streak + 1;
      else if (last !== today()) {
        if (last && last < daysAgo(3)) comeback = true;
        streak = 1;
      }
      db.prepare("UPDATE users SET streak = ?, best_streak = MAX(best_streak, ?), last_quiz_date = ? WHERE id = ?")
        .run(streak, streak, today(), user.id);
    }

    if (xpEarned > 0) {
      db.prepare("UPDATE users SET xp = xp + ? WHERE id = ?").run(xpEarned, user.id);
      const xpReason = kind === "daily" ? "offline_daily_quest" : "offline_practice_round";
      db.prepare("INSERT INTO xp_events (user_id, amount, reason, date) VALUES (?, ?, ?, ?)")
        .run(user.id, xpEarned, xpReason, today());
    }

    const fresh = db.prepare("SELECT * FROM users WHERE id = ?").get(user.id);
    const newAwards = checkAwards(user.id, { comeback }).map(({ earned, ...a }) => a);

    return res.json({
      score: offlineScore,
      total,
      xpEarned,
      xp: fresh.xp,
      level: levelForXp(fresh.xp),
      streak: fresh.streak,
      newAwards,
      correct: [],
      syncedOffline: true,
    });
  }

  const quiz = db.prepare("SELECT * FROM quizzes WHERE id = ? AND user_id = ? AND kind = ?").get(quizId, user.id, kind);
  if (!quiz) return res.status(404).json({ error: "Quiz not found" });
  if (quiz.completed) return res.status(400).json({ error: "Already completed" });
  if (!Array.isArray(answers)) return res.status(400).json({ error: "Answers required" });

  const ids = JSON.parse(quiz.question_ids);
  const ph = ids.map(() => "?").join(",");
  const questions = db.prepare(`SELECT * FROM questions WHERE id IN (${ph})`).all(...ids);
  const byId = Object.fromEntries(questions.map((q) => [q.id, q]));

  let score = 0;
  let xpEarned = 0;
  const correct = [];
  const logStmt = db.prepare(
    "INSERT INTO answer_log (user_id, question_id, subject, country, correct, source, date) VALUES (?, ?, ?, ?, ?, ?, ?)"
  );
  for (const qid of ids) {
    const q = byId[qid];
    if (!q) continue;

    // Robust answer lookup:
    // Match question ID loosely / numerically, and prioritize the latest non-null choice if duplicate entries exist
    const matchingAnswers = answers.filter((a) => a && Number(a.questionId) === Number(qid));
    let ans = null;
    if (matchingAnswers.length > 0) {
      const nonNullAns = matchingAnswers.filter((a) => a.choice !== null && a.choice !== undefined);
      ans = nonNullAns.length > 0 ? nonNullAns[nonNullAns.length - 1] : matchingAnswers[matchingAnswers.length - 1];
    }

    const order = optionOrder(quiz.id, qid);
    const correctIndex = order.indexOf(q.correct_index);
    correct.push({
      questionId: qid,
      correctIndex,
    });

    const isCorrect = ans != null && ans.choice !== null && ans.choice !== undefined && Number(ans.choice) === correctIndex;

    if (isCorrect) {
      score += 1;
      if (kind === "daily") {
        xpEarned += 10;
        if (typeof ans.timeMs === "number" && ans.timeMs < 5000) xpEarned += 5;
      } else {
        xpEarned += 8;
      }
    } else if (kind === "daily") {
      xpEarned -= 2; // quiet cost, never floors below 0 for the quiz overall
    }
    logStmt.run(user.id, qid, q.subject, q.country, isCorrect ? 1 : 0, kind, today());
  }
  xpEarned = Math.max(0, xpEarned);

  let streak = user.streak;
  let comeback = false;
  if (kind === "daily") {
    const last = user.last_quiz_date;
    if (last === daysAgo(1)) streak = user.streak + 1;
    else if (last !== today()) {
      if (last && last < daysAgo(3)) comeback = true;
      streak = 1;
    }
    db.prepare("UPDATE users SET streak = ?, best_streak = MAX(best_streak, ?), last_quiz_date = ? WHERE id = ?")
      .run(streak, streak, today(), user.id);
  }

  db.prepare("UPDATE quizzes SET completed = 1, score = ?, xp_earned = ? WHERE id = ?").run(score, xpEarned, quiz.id);
  db.prepare("UPDATE users SET xp = xp + ? WHERE id = ?").run(xpEarned, user.id);
  if (xpEarned > 0) {
    const xpReason = kind === "daily" ? "daily_quest" : kind === "practice" ? "practice_round" : "revenge_round";
    db.prepare("INSERT INTO xp_events (user_id, amount, reason, date) VALUES (?, ?, ?, ?)")
      .run(user.id, xpEarned, xpReason, today());
  }

  const fresh = db.prepare("SELECT * FROM users WHERE id = ?").get(user.id);
  const newAwards = checkAwards(user.id, { comeback }).map(({ earned, ...a }) => a);
  res.json({
    score,
    total: ids.length,
    xpEarned,
    xp: fresh.xp,
    level: levelForXp(fresh.xp),
    streak: fresh.streak,
    newAwards,
    correct,
  });
}

router.post("/quiz/daily/submit", (req, res) => submitQuiz(req, res, "daily"));
router.post("/quiz/practice/submit", (req, res) => submitQuiz(req, res, "practice"));
router.post("/quiz/revenge/submit", (req, res) => submitQuiz(req, res, "revenge"));
// Compatibility aliases for legacy/offline queue submissions
router.post("/quizzes/daily/submit", (req, res) => submitQuiz(req, res, "daily"));
router.post("/quizzes/practice/submit", (req, res) => submitQuiz(req, res, "practice"));
router.post("/quizzes/revenge/submit", (req, res) => submitQuiz(req, res, "revenge"));

// ---------- Battles history ----------

router.get("/battles/history", (req, res) => {
  const uid = req.user.id;
  ensureDemoBattle(uid);
  const rows = db
    .prepare("SELECT * FROM battles WHERE p1 = ? OR p2 = ? ORDER BY id DESC LIMIT 30")
    .all(uid, uid);
  const battles = rows.map((b) => {
    const mine = b.p1 === uid;
    const oppId = mine ? b.p2 : b.p1;
    const opp = db.prepare("SELECT name FROM users WHERE id = ?").get(oppId);
    const myScore = mine ? b.s1 : b.s2;
    const theirScore = mine ? b.s2 : b.s1;
    return {
      id: b.id,
      opponentName: opp ? opp.name || "Player" : "Player",
      myScore,
      theirScore,
      result: b.winner == null ? "draw" : b.winner === uid ? "win" : "loss",
      date: b.date,
    };
  });
  res.json({ battles });
});

// ---------- Leaderboard ----------

router.get("/leaderboard", (req, res) => {
  const user = req.user;
  const scope = ["class", "school", "friends"].includes(req.query.scope) ? req.query.scope : "class";

  let members;
  if (scope === "friends") {
    const ids = db.prepare("SELECT friend_id FROM friendships WHERE user_id = ?").all(user.id).map((r) => r.friend_id);
    ids.push(user.id);
    const ph = ids.map(() => "?").join(",");
    members = db.prepare(`SELECT * FROM users WHERE id IN (${ph})`).all(...ids);
  } else if (scope === "school" && user.school_id) {
    members = db.prepare("SELECT * FROM users WHERE school_id = ? AND role = 'student'").all(user.school_id);
  } else {
    // class scope: same grade (same school when known)
    members = user.school_id
      ? db.prepare("SELECT * FROM users WHERE grade = ? AND school_id = ? AND role = 'student'").all(user.grade, user.school_id)
      : db.prepare("SELECT * FROM users WHERE grade = ? AND role = 'student'").all(user.grade);
  }
  if (!members.some((m) => m.id === user.id)) members.push(user);

  const ws = weekStart();
  const xpStmt = db.prepare("SELECT COALESCE(SUM(amount),0) s FROM xp_events WHERE user_id = ? AND date >= ?");
  const entries = members
    .map((m) => ({
      userId: m.id,
      name: m.name || "Player",
      avatar: JSON.parse(m.avatar || "{}"),
      weeklyXp: xpStmt.get(m.id, ws).s,
      isMe: m.id === user.id,
    }))
    .sort((a, b) => b.weeklyXp - a.weeklyXp || a.userId - b.userId)
    .map((e, i) => ({ ...e, rank: i + 1 }));

  const me = entries.find((e) => e.isMe);
  const top3 = entries.slice(0, 3);
  // Neighborhood: 2 above and 2 below the student — never the full ranking.
  const start = Math.max(0, me.rank - 3);
  const neighborhood = entries.slice(start, me.rank + 2);
  res.json({ scope, top3, neighborhood, me });
});

// ---------- Friends ----------

router.get("/friends", (req, res) => {
  ensureDemoFriend(req.user.id);
  const ids = db.prepare("SELECT friend_id FROM friendships WHERE user_id = ?").all(req.user.id).map((r) => r.friend_id);
  const friends = ids
    .map((id) => db.prepare("SELECT * FROM users WHERE id = ?").get(id))
    .filter(Boolean)
    .map((f) => ({
      userId: f.id,
      name: f.name || "Player",
      avatar: JSON.parse(f.avatar || "{}"),
      level: levelForXp(f.xp),
      streak: f.streak,
      online: isOnline(f.id),
    }));
  res.json({ friends });
});

router.post("/friends/add", (req, res) => {
  const fid = parseFriendCode(req.body.friendCode);
  if (!fid) return res.status(400).json({ error: "That doesn't look like a friend code (QQ-000123)" });
  if (fid === req.user.id) return res.status(400).json({ error: "That's your own code!" });
  const friend = db.prepare("SELECT * FROM users WHERE id = ?").get(fid);
  if (!friend) return res.status(404).json({ error: "No player found with that code" });
  db.prepare("INSERT OR IGNORE INTO friendships (user_id, friend_id) VALUES (?, ?)").run(req.user.id, fid);
  db.prepare("INSERT OR IGNORE INTO friendships (user_id, friend_id) VALUES (?, ?)").run(fid, req.user.id);
  res.json({
    friend: {
      userId: friend.id,
      name: friend.name || "Player",
      avatar: JSON.parse(friend.avatar || "{}"),
      level: levelForXp(friend.xp),
      streak: friend.streak,
      online: isOnline(friend.id),
    },
  });
});

// ---------- Word Search (शब्द खोज) ----------

const WORD_SEARCH_CATEGORIES = [
  {
    id: "nepal_heritage",
    titleEn: "Nepal Heritage & Culture",
    titleNe: "नेपाली सम्पदा र संस्कृति",
    icon: "🏔️",
    words: [
      { word: "SAGARMATHA", clueEn: "Highest peak in the world", clueNe: "विश्वको सर्वोच्च शिखर" },
      { word: "POKHARA", clueEn: "Scenic lake city of Nepal", clueNe: "नेपालको सुन्दर तालहरूको सहर" },
      { word: "LUMBINI", clueEn: "Birthplace of Lord Buddha", clueNe: "भगवान बुद्धको जन्मस्थल" },
      { word: "DANFE", clueEn: "National bird of Nepal", clueNe: "नेपालको राष्ट्रिय चरा (डाँफे)" },
      { word: "RHINO", clueEn: "One-horned icon of Chitwan", clueNe: "चितवनको एक सिङ्गे गैँडा" },
      { word: "BAGMATI", clueEn: "Holy river flowing past Pashupatinath", clueNe: "पशुपतिनाथ भएर बग्ने पवित्र नदी" },
      { word: "PATAN", clueEn: "Historic City of Fine Arts", clueNe: "ललितकलाको प्राचीन सहर" },
      { word: "JANAKPUR", clueEn: "City of Mithila and Janaki Temple", clueNe: "जानकी मन्दिर अवस्थित मिथिला नगरी" },
      { word: "BHAKTAPUR", clueEn: "City of devotees & 55-window palace", clueNe: "५५ झ्याले दरबार भएको भक्तपुर" },
      { word: "PASHUPATI", clueEn: "Sacred Hindu pilgrimage temple", clueNe: "पवित्र हिन्दू तीर्थस्थल पशुपतिनाथ" },
      { word: "GORKHA", clueEn: "Historic palace of King Prithvi Narayan", clueNe: "गोरखा दरबार, ऐतिहासिक किल्ला" },
      { word: "ILAM", clueEn: "Famous tea garden hills of eastern Nepal", clueNe: "चियाबारीले प्रसिद्ध पूर्वी जिल्ला" },
      { word: "BOUDDHA", clueEn: "Massive Buddhist stupa in Kathmandu", clueNe: "काठमाडौँको विशाल बौद्ध स्तुपा" },
      { word: "SWAYAMBHU", clueEn: "Ancient hilltop monkey temple stupa", clueNe: "स्वयम्भूनाथ महाचैत्य" },
      { word: "ANNAPURNA", clueEn: "World famous trekking massif", clueNe: "अन्नपूर्ण पदमार्ग हिमशृङ्खला" },
      { word: "MANASLU", clueEn: "Mountain of the spirit in Gorkha", clueNe: "मनास्लु हिमाल" },
      { word: "PALPA", clueEn: "Historic Tansen hill town & Dhaka", clueNe: "पाल्पा तानसेन, ढाकाको सहर" },
    ]
  },
  {
    id: "solar_system",
    titleEn: "Cosmos & Solar System",
    titleNe: "सौर्यमण्डल र अन्तरिक्ष",
    icon: "🪐",
    words: [
      { word: "JUPITER", clueEn: "The largest planet in solar system", clueNe: "सौर्यमण्डलको सबैभन्दा ठूलो ग्रह" },
      { word: "MERCURY", clueEn: "Closest planet to the Sun", clueNe: "सूर्यको सबैभन्दा नजिकको ग्रह" },
      { word: "NEPTUNE", clueEn: "Farthest giant gas planet from Sun", clueNe: "सूर्यबाट सबैभन्दा टाढाको ग्रह" },
      { word: "GALAXY", clueEn: "Vast system of stars, like Milky Way", clueNe: "तारापुञ्ज (मिल्की वे जस्तै)" },
      { word: "ASTEROID", clueEn: "Rocky celestial body orbiting Sun", clueNe: "सूर्य वरिपरि घुम्ने चट्टानी पिण्ड" },
      { word: "COMET", clueEn: "Cosmic snowball with a shining tail", clueNe: "चम्किलो पुच्छ्रेतारा" },
      { word: "ORBIT", clueEn: "Curved path of a celestial body", clueNe: "ग्रहहरूको परिक्रमा मार्ग" },
      { word: "SATURN", clueEn: "Planet with spectacular ice rings", clueNe: "सुन्दर घेरा भएको शनि ग्रह" },
      { word: "VENUS", clueEn: "Brightest morning and evening planet", clueNe: "सबैभन्दा चम्किलो शुक्र ग्रह" },
      { word: "MARS", clueEn: "The famous Red Planet", clueNe: "रातो ग्रह मङ्गल" },
      { word: "URANUS", clueEn: "Sideways-spinning ice giant", clueNe: "ढल्किएर घुम्ने अरुण ग्रह" },
      { word: "ECLIPSE", clueEn: "Celestial body passing into shadow", clueNe: "ग्रहण (सूर्य वा चन्द्र ग्रहण)" },
      { word: "METEOR", clueEn: "Shooting star burning in atmosphere", clueNe: "उल्कापिण्ड" },
      { word: "NEBULA", clueEn: "Giant interstellar cloud of gas & dust", clueNe: "निहारिका, तारा बन्ने स्थान" },
      { word: "CRATER", clueEn: "Bowl-shaped impact depression on moon", clueNe: "चन्द्रमाको खाल्डो" },
    ]
  },
  {
    id: "science_elements",
    titleEn: "Science & Nature",
    titleNe: "विज्ञान र प्रकृति",
    icon: "🔬",
    words: [
      { word: "OXYGEN", clueEn: "Gas essential for respiration", clueNe: "श्वासप्रश्वासका लागि चाहिने प्राणवायु" },
      { word: "HYDROGEN", clueEn: "Most abundant element in universe", clueNe: "ब्रह्माण्डमा सबैभन्दा बढी पाइने तत्त्व" },
      { word: "GRAVITY", clueEn: "Force that pulls objects downward", clueNe: "पृथ्वीको गुरुत्वाकर्षण बल" },
      { word: "ENERGY", clueEn: "Capacity to perform work", clueNe: "कार्य गर्ने क्षमता (ऊर्जा)" },
      { word: "ELECTRON", clueEn: "Negatively charged subatomic particle", clueNe: "ऋणात्मक चार्ज भएको कण" },
      { word: "PRISM", clueEn: "Refracts light into 7 colors", clueNe: "प्रकाशलाई सात रङमा छुट्याउने साधन" },
      { word: "CARBON", clueEn: "Found in all living organic structures", clueNe: "सम्पूर्ण जैविक पदार्थको आधार तत्त्व" },
      { word: "NITROGEN", clueEn: "Makes up 78% of Earth atmosphere", clueNe: "हावामा ७८% पाइने ग्यास" },
      { word: "DENSITY", clueEn: "Mass per unit volume of a substance", clueNe: "घनत्व" },
      { word: "VOLTAGE", clueEn: "Electrical potential difference", clueNe: "विद्युतीय भोल्टेज" },
      { word: "MAGNET", clueEn: "Material attracting iron objects", clueNe: "चुम्बक" },
      { word: "INERTIA", clueEn: "Tendency to resist changes in motion", clueNe: "चाल वा विश्रामको गुण (जडता)" },
      { word: "FRICTION", clueEn: "Force opposing sliding contact", clueNe: "घर्षण बल" },
      { word: "PHOTON", clueEn: "Particle representing light quantum", clueNe: "प्रकाशको सूक्ष्म कण (फोटोन)" },
    ]
  },
  {
    id: "wildlife_nature",
    titleEn: "Himalayan Wildlife",
    titleNe: "वन्यजन्तु र प्रकृति",
    icon: "🐾",
    words: [
      { word: "REDPANDA", clueEn: "Cute bamboo eater of Langtang", clueNe: "लाङटाङको दुर्लभ हाब्रे (रेड पाण्डा)" },
      { word: "TIGER", clueEn: "Royal Bengal predator of Bardia", clueNe: "बर्दियाको पाटे बाघ" },
      { word: "ELEPHANT", clueEn: "Gentle giant of the Tarai plains", clueNe: "तराईको विशाल हात्ती" },
      { word: "GHARIAL", clueEn: "Fish-eating long-snouted crocodile", clueNe: "माछा खाने घडियाल गोही" },
      { word: "LEOPARD", clueEn: "Elusive spotted cat of the hills", clueNe: "पहाडी क्षेत्रको चितुवा" },
      { word: "PEACOCK", clueEn: "Colorful dancing bird with feathers", clueNe: "रङ्गीचङ्गी प्वाँख भएको मयूर" },
      { word: "MUSKDEER", clueEn: "High altitude deer prized for musk", clueNe: "कस्तुरी मृग" },
      { word: "SNOWLEOPARD", clueEn: "Ghost of high Himalayan ridges", clueNe: "हिउँ चितुवा" },
      { word: "MONAL", clueEn: "Glistening pheasant of high peaks", clueNe: "मुनाल चरा" },
      { word: "DOLPHIN", clueEn: "Gangetic freshwater mammal of Karnali", clueNe: "कर्णालीको सोँस (डल्फिन)" },
      { word: "PANGOLIN", clueEn: "Scaly anteater of Nepal forests", clueNe: "सङ्कटापन्न सालक" },
      { word: "HORNBILL", clueEn: "Giant beaked bird of Chitwan canopy", clueNe: "धनेश चरा" },
      { word: "VULTURE", clueEn: "Nature essential scavenger raptor", clueNe: "प्रकृतिको कुचीकार (गिद्ध)" },
    ]
  },
  {
    id: "body_health",
    titleEn: "Human Body & Health",
    titleNe: "मानव शरीर र स्वास्थ्य",
    icon: "🫀",
    words: [
      { word: "HEART", clueEn: "Pumps oxygen-rich blood through body", clueNe: "शरीरमा रगत पम्प गर्ने अङ्ग (मुटु)" },
      { word: "BRAIN", clueEn: "Command center of nervous system", clueNe: "स्नायु प्रणालीको नियन्त्रक (मस्तिष्क)" },
      { word: "MUSCLE", clueEn: "Tissue that helps body move", clueNe: "शरीर चलायमान बनाउने मांशपेसी" },
      { word: "SKELETON", clueEn: "Internal framework of 206 bones", clueNe: "२०६ वटा हाड मिलेर बनेको अस्थिपञ्जर" },
      { word: "VITAMIN", clueEn: "Nutrient that keeps immunity strong", clueNe: "रोग प्रतिरोधात्मक क्षमता बढाउने तत्त्व" },
      { word: "ARTERY", clueEn: "Vessel carrying oxygenated blood", clueNe: "मुटुबाट शुद्ध रगत लैजाने धमनी" },
      { word: "NEURON", clueEn: "Nerve cell transmitting signals", clueNe: "सूचना प्रवाह गर्ने स्नायु कोष" },
      { word: "LIVER", clueEn: "Body largest metabolic and detox organ", clueNe: "शरीरको सबैभन्दा ठूलो ग्रन्थी (कलेजो)" },
      { word: "KIDNEY", clueEn: "Bean-shaped blood filtering organ", clueNe: "रगत छान्ने मिर्गौला" },
      { word: "LUNGS", clueEn: "Organs exchanging oxygen and carbon", clueNe: "श्वासप्रश्वास अङ्ग फोक्सो" },
      { word: "CALCIUM", clueEn: "Mineral strengthening teeth and bones", clueNe: "हाड बलियो बनाउने क्याल्सियम" },
      { word: "PROTEIN", clueEn: "Building block for muscle repair", clueNe: "मांशपेसी निर्माण गर्ने प्रोटिन" },
    ]
  },
  {
    id: "nepal_geography",
    titleEn: "Geography of Nepal",
    titleNe: "नेपालको भूगोल",
    icon: "🗺️",
    words: [
      { word: "HIMALAYA", clueEn: "Majestic snow-capped mountain range", clueNe: "सेता हिउँका चुचुराहरूको हिमशृङ्खला" },
      { word: "KARNALI", clueEn: "Longest river flowing in Nepal", clueNe: "नेपालको सबैभन्दा लामो नदी" },
      { word: "MUSTANG", clueEn: "Ancient kingdom beyond the high hills", clueNe: "मुस्ताङ, हिमाल पारिको जिल्ला" },
      { word: "CHITWAN", clueEn: "Home of Nepal's first national park", clueNe: "नेपालको पहिलो राष्ट्रिय निकुञ्ज" },
      { word: "KOSHI", clueEn: "River with largest water discharge", clueNe: "सबैभन्दा बढी जलप्रवाह भएको नदी" },
      { word: "TERAI", clueEn: "Fertile southern flat grain basket", clueNe: "उब्जाउ अन्नको भण्डार (तराई)" },
      { word: "RARA", clueEn: "Deepest and biggest lake in Mugu", clueNe: "मुगुमा अवस्थित रारा ताल" },
      { word: "GANDAKI", clueEn: "Mighty river fed by Kali & Trishuli", clueNe: "गण्डकी नदी" },
      { word: "PHEWA", clueEn: "Famous lake reflecting Machhapuchhre", clueNe: "पोखराको फेवाताल" },
      { word: "TILICHO", clueEn: "One of the highest altitude alpine lakes", clueNe: "विश्वकै अग्लो स्थानको तिलिचो ताल" },
      { word: "DOLPA", clueEn: "Largest district of Nepal with Shey Phoksundo", clueNe: "नेपालको सबैभन्दा ठूलो जिल्ला डोल्पा" },
      { word: "MANANG", clueEn: "Rain-shadow valley district behind Annapurna", clueNe: "मनाङ उपत्यका" },
    ]
  },
  {
    id: "nepali_culture",
    titleEn: "Festivals & Traditional Arts",
    titleNe: "चाडपर्व र मौलिक कला",
    icon: "🪕",
    words: [
      { word: "DASHAIN", clueEn: "Biggest autumn festival with Jamara & Tika", clueNe: "नेपालीहरूको महान् चाड बडादसैँ" },
      { word: "TIHAR", clueEn: "Festival of lights, flowers, and brothers", clueNe: "उज्यालो र फूलको चाड तिहार" },
      { word: "CHHATH", clueEn: "Sun-worship festival of the plains", clueNe: "सूर्य उपासनाको पर्व छठ" },
      { word: "LOSHAR", clueEn: "New year festival of Himalayan communities", clueNe: "हिमाली नयाँ वर्ष ल्होसार" },
      { word: "KHUKURI", clueEn: "Traditional curved Nepali bravery blade", clueNe: "नेपाली वीरताको प्रतीक खुकुरी" },
      { word: "MADAL", clueEn: "Beloved double-headed rhythmic hand drum", clueNe: "नेपाली मौलिक बाजा मादल" },
      { word: "SARANGI", clueEn: "Folk string instrument played with a bow", clueNe: "सारङ्गी बाजा" },
      { word: "SELROTI", clueEn: "Traditional crispy ring-shaped rice bread", clueNe: "नेपाली मौलिक परिकार सेलरोटी" },
      { word: "DHAKA", clueEn: "Intricately hand-woven traditional fabric", clueNe: "ढाका टोपी र कपडा" },
      { word: "CHAUTARI", clueEn: "Shady stone resting tree platform in hills", clueNe: "वर-पीपलको शीतल चौतारी" },
    ]
  }
];

function getDailyWordSearchCategory(dateStr) {
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    hash = (hash * 31 + dateStr.charCodeAt(i)) >>> 0;
  }
  const index = hash % WORD_SEARCH_CATEGORIES.length;
  const category = WORD_SEARCH_CATEGORIES[index];

  // Pick deterministic subset of 7 words based on dateStr hash
  const shuffled = [...category.words].sort((a, b) => {
    const ha = (hash ^ a.word.charCodeAt(0)) % 100;
    const hb = (hash ^ b.word.charCodeAt(0)) % 100;
    return ha - hb;
  });

  return {
    ...category,
    words: shuffled.slice(0, 7),
  };
}

router.get("/wordsearch/daily", (req, res) => {
  const dateStr = req.query.date || today();
  const categoryData = getDailyWordSearchCategory(dateStr);

  // Check if player has already submitted for today
  const myScoreRow = db
    .prepare("SELECT * FROM word_search_scores WHERE user_id = ? AND puzzle_date = ?")
    .get(req.user.id, dateStr);

  const myScore = myScoreRow
    ? {
        timeSeconds: myScoreRow.time_seconds,
        wordsFound: myScoreRow.words_found,
        totalWords: myScoreRow.total_words,
        stars: myScoreRow.stars,
        xpEarned: myScoreRow.xp_earned,
        completedAt: myScoreRow.created_at,
      }
    : null;

  // Fastest solvers leaderboard for today
  const leaderboard = db
    .prepare(`
      SELECT u.id, u.name, u.avatar, s.time_seconds, s.words_found
      FROM word_search_scores s
      JOIN users u ON s.user_id = u.id
      WHERE s.puzzle_date = ?
      ORDER BY s.words_found DESC, s.time_seconds ASC
      LIMIT 10
    `)
    .all(dateStr)
    .map((row, idx) => ({
      rank: idx + 1,
      userId: row.id,
      name: row.name || "Player",
      avatar: JSON.parse(row.avatar || "{}"),
      timeSeconds: row.time_seconds,
      wordsFound: row.words_found,
      isMe: row.id === req.user.id,
    }));

  res.json({
    puzzleDate: dateStr,
    category: categoryData.id,
    titleEn: categoryData.titleEn,
    titleNe: categoryData.titleNe,
    icon: categoryData.icon,
    words: categoryData.words,
    allCategories: WORD_SEARCH_CATEGORIES.map(c => ({ id: c.id, titleEn: c.titleEn, titleNe: c.titleNe, icon: c.icon, wordCount: c.words.length })),
    myScore,
    leaderboard,
  });
});

// Random Word Search for unlimited practice sessions with fresh boards
router.get("/wordsearch/random", (req, res) => {
  const catId = req.query.category;
  let category = WORD_SEARCH_CATEGORIES.find(c => c.id === catId);
  if (!category) {
    category = WORD_SEARCH_CATEGORIES[Math.floor(Math.random() * WORD_SEARCH_CATEGORIES.length)];
  }

  // Pick 7 random words from the pool
  const shuffled = [...category.words].sort(() => 0.5 - Math.random());
  const selectedWords = shuffled.slice(0, 7);

  res.json({
    category: category.id,
    titleEn: category.titleEn,
    titleNe: category.titleNe,
    icon: category.icon,
    words: selectedWords,
    allCategories: WORD_SEARCH_CATEGORIES.map(c => ({
      id: c.id,
      titleEn: c.titleEn,
      titleNe: c.titleNe,
      icon: c.icon,
      wordCount: c.words.length,
    })),
  });
});

router.post(["/wordsearch/submit", "/games/wordsearch/daily/score"], (req, res) => {
  const { puzzleDate, category = "daily", timeSeconds, wordsFound, totalWords, stars = 3 } = req.body || {};
  const dateStr = puzzleDate || today();

  if (typeof timeSeconds !== "number" || typeof wordsFound !== "number") {
    return res.status(400).json({ error: "Invalid score payload" });
  }

  const xpEarned = Math.round(25 + (wordsFound / Math.max(1, totalWords)) * 25 + Math.min(3, Math.max(1, stars)) * 5);

  const existing = db
    .prepare("SELECT * FROM word_search_scores WHERE user_id = ? AND puzzle_date = ?")
    .get(req.user.id, dateStr);

  if (!existing) {
    db.prepare(`
      INSERT INTO word_search_scores (user_id, puzzle_date, category, time_seconds, words_found, total_words, stars, xp_earned)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `).run(req.user.id, dateStr, category, timeSeconds, wordsFound, totalWords, stars, xpEarned);

    db.prepare("UPDATE users SET xp = xp + ? WHERE id = ?").run(xpEarned, req.user.id);
    db.prepare("INSERT INTO xp_events (user_id, amount, reason, date) VALUES (?, ?, 'word_search', ?)")
      .run(req.user.id, xpEarned, today());
  }

  const freshUser = db.prepare("SELECT * FROM users WHERE id = ?").get(req.user.id);

  res.json({
    ok: true,
    score: {
      puzzleDate: dateStr,
      timeSeconds,
      wordsFound,
      totalWords,
      stars,
      xpEarned: existing ? 0 : xpEarned,
      isNewRecord: !existing,
    },
    user: serializeUser(freshUser),
  });
});

// ---------- Student Game Insights & Mastery ----------

router.get("/me/insights", (req, res) => {
  const userId = req.user.id;
  const user = db.prepare("SELECT * FROM users WHERE id = ?").get(userId);

  // 1. Overall stats
  const totalAnswersRow = db
    .prepare("SELECT COUNT(*) as total, COALESCE(SUM(correct), 0) as correct FROM answer_log WHERE user_id = ?")
    .get(userId);
  const totalAnswers = totalAnswersRow ? totalAnswersRow.total : 0;
  const correctAnswers = totalAnswersRow ? totalAnswersRow.correct : 0;
  const accuracyPct = totalAnswers > 0 ? Math.round((correctAnswers / totalAnswers) * 100) : 0;

  // 2. Subject Mastery Breakdown
  const subjectRows = db
    .prepare(`
      SELECT subject, COUNT(*) as total, COALESCE(SUM(correct), 0) as correct
      FROM answer_log
      WHERE user_id = ?
      GROUP BY subject
      ORDER BY total DESC
    `)
    .all(userId);

  const subjectMastery = subjectRows.map(row => ({
    subject: row.subject,
    total: row.total,
    correct: row.correct,
    pct: row.total > 0 ? Math.round((row.correct / row.total) * 100) : 0,
  }));

  // 3. Game XP and Play Distribution
  const xpBreakdownRows = db
    .prepare(`
      SELECT reason, COALESCE(SUM(amount), 0) as totalXp, COUNT(*) as playCount
      FROM xp_events
      WHERE user_id = ?
      GROUP BY reason
    `)
    .all(userId);

  const gameMeta = {
    daily_quest: { name: "Daily Quest", icon: "🎯", color: "#F59E0B" },
    practice_round: { name: "Unlimited Practice", icon: "📚", color: "#3B82F6" },
    daily_zip: { name: "Zip Path Puzzle", icon: "⚡", color: "#8B5CF6" },
    word_search: { name: "Word Search", icon: "🔤", color: "#EC4899" },
    daily_riddle: { name: "Gaunkhane Katha", icon: "🧩", color: "#10B981" },
    memory_blocks: { name: "Memory Blocks", icon: "🧠", color: "#06B6D4" },
    battle_win: { name: "Friend Battles", icon: "⚔️", color: "#EF4444" },
    quiz_streak: { name: "Streak Bonus", icon: "🔥", color: "#F97316" },
  };

  const gameBreakdown = xpBreakdownRows.map(r => {
    const meta = gameMeta[r.reason] || { name: r.reason, icon: "⭐", color: "#6B7280" };
    return {
      reason: r.reason,
      name: meta.name,
      icon: meta.icon,
      color: meta.color,
      totalXp: r.totalXp,
      playCount: r.playCount,
    };
  });

  // 4. 30-Day Activity Heatmap
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
  const thirtyDaysAgoStr = thirtyDaysAgo.toISOString().split("T")[0];

  const dailyXpRows = db
    .prepare(`
      SELECT date, COALESCE(SUM(amount), 0) as xp, COUNT(*) as events
      FROM xp_events
      WHERE user_id = ? AND date >= ?
      GROUP BY date
      ORDER BY date ASC
    `)
    .all(userId, thirtyDaysAgoStr);

  const dailyAnswersRows = db
    .prepare(`
      SELECT date, COUNT(*) as count, COALESCE(SUM(correct), 0) as correct
      FROM answer_log
      WHERE user_id = ? AND date >= ?
      GROUP BY date
    `)
    .all(userId, thirtyDaysAgoStr);

  const answerMap = new Map();
  dailyAnswersRows.forEach(row => {
    answerMap.set(row.date, row);
  });

  const activityHeatmap = [];
  for (let i = 29; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    const dStr = d.toISOString().split("T")[0];
    const xpEntry = dailyXpRows.find(x => x.date === dStr);
    const ansEntry = answerMap.get(dStr);

    activityHeatmap.push({
      date: dStr,
      xp: xpEntry ? xpEntry.xp : 0,
      events: xpEntry ? xpEntry.events : 0,
      answers: ansEntry ? ansEntry.count : 0,
      correct: ansEntry ? ansEntry.correct : 0,
    });
  }

  // 5. Personal Bests
  const fastestZip = db
    .prepare("SELECT MIN(time_seconds) as fastest FROM daily_zip_scores WHERE user_id = ?")
    .get(userId);

  const fastestWordSearch = db
    .prepare("SELECT MIN(time_seconds) as fastest FROM word_search_scores WHERE user_id = ?")
    .get(userId);

  const riddlesSolved = db
    .prepare("SELECT COUNT(*) as count FROM user_riddle_solves WHERE user_id = ?")
    .get(userId);

  const battlesWon = db
    .prepare("SELECT COUNT(*) as count FROM battles WHERE winner = ?")
    .get(userId);

  const totalBattles = db
    .prepare("SELECT COUNT(*) as count FROM battles WHERE p1 = ? OR p2 = ?")
    .get(userId, userId);

  const wordSearchCount = db
    .prepare("SELECT COUNT(*) as count FROM word_search_scores WHERE user_id = ?")
    .get(userId);

  const memoryBest = db
    .prepare("SELECT MAX(stars) as stars, MIN(time_ms) as minTime FROM memory_scores WHERE user_id = ?")
    .get(userId);

  res.json({
    summary: {
      totalXp: user.xp,
      level: levelForXp(user.xp),
      streak: user.streak,
      totalAnswers,
      correctAnswers,
      accuracyPct,
    },
    subjectMastery,
    gameBreakdown,
    activityHeatmap,
    personalBests: {
      fastestZipSec: fastestZip && fastestZip.fastest ? fastestZip.fastest : null,
      fastestWordSearchSec: fastestWordSearch && fastestWordSearch.fastest ? fastestWordSearch.fastest : null,
      wordSearchCount: wordSearchCount ? wordSearchCount.count : 0,
      totalRiddlesSolved: riddlesSolved ? riddlesSolved.count : 0,
      battlesWon: battlesWon ? battlesWon.count : 0,
      totalBattles: totalBattles ? totalBattles.count : 0,
      memoryHighestStars: memoryBest && memoryBest.stars ? memoryBest.stars : null,
    },
  });
});

// ---------- Awards ----------

router.get("/awards", (req, res) => {
  res.json({ awards: awardsForUser(req.user.id) });
});

export default router;
