# fly.toml app configuration file generated for quizquest-api on 2026-09-06T16:20:44+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quizquest-api'
primary_region = 'iad'

[build]
[[mounts]]
  source = 'quizquest_data'
  destination = '/app/data'
  initial_size = '1GB'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
