import db from "../db.js";
import { pushDigestNotification } from "./notifications.js";
import { GRADE_BANDS } from "../util.js";

const TIMEZONE = process.env.DIGEST_TIMEZONE || "Asia/Kathmandu";
const SCHEDULE_HOUR = Number(process.env.DIGEST_SCHEDULE_HOUR ?? 7);
const SCHEDULE_MINUTE = Number(process.env.DIGEST_SCHEDULE_MINUTE ?? 0);

let lastRunDate = null;
let timerId = null;

/**
 * Returns current time parts in the configured timezone.
 */
export function getLocalTime(tz = TIMEZONE) {
  const now = new Date();
  const formatter = new Intl.DateTimeFormat("en-US", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  });

  const parts = formatter.formatToParts(now);
  const find = (type) => parts.find((p) => p.type === type)?.value;

  const year = find("year");
  const month = find("month");
  const day = find("day");
  const hour = Number(find("hour"));
  const minute = Number(find("minute"));
  const second = Number(find("second"));

  return {
    isoDate: `${year}-${month}-${day}`,
    hour,
    minute,
    second,
    formatted: `${year}-${month}-${day} ${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")}:${String(second).padStart(2, "0")}`,
    timezone: tz,
  };
}

/**
 * Auto-generates a set of 3 grade-band digests for a given date if missing.
 */
export function autoGenerateDigestsForDate(dateStr) {
  const created = [];
  const existing = db.prepare("SELECT grade_band FROM digests WHERE date = ?").all(dateStr);
  const existingBands = new Set(existing.map((e) => e.grade_band));

  // Seed pool of inspiring facts
  const gkPool = [
    { en: "Honey never spoils: archaeologists found 3,000-year-old honey in Egyptian tombs that is still completely edible!", ne: "मह कहिल्यै बिग्रँदैन: पुरातत्वविद्हरूले इजिप्टका चिहानहरूमा ३००० वर्ष पुरानो खानयोग्य मह भेट्टाएका छन्।" },
    { en: "Octopuses have three hearts and blue blood!", ne: "अक्टोपसका तीनवटा मुटु र नीलो रगत हुन्छ!" },
    { en: "A day on planet Venus is longer than an entire year on Venus.", ne: "शुक्र ग्रहको एक दिन उसको एक वर्षभन्दा पनि लामो हुन्छ।" },
    { en: "Bananas are curved because they grow towards the sun against gravity (negative geotropism).", ne: "केरा गुरुत्वाकर्षणको विपरित सूर्यतर्फ फर्केर हुर्कने भएकाले बाङ्गो हुन्छ।" },
    { en: "Sound travels about 4 times faster through water than through air.", ne: "ध्वनि हावामा भन्दा पानीमा करिब ४ गुणा छिटो यात्रा गर्छ।" },
  ];

  const nepalPool = [
    { en: "Nepal is home to Mount Everest (8,848.86m), the highest peak in the world, known locally as Sagarmatha.", ne: "नेपालमा विश्वको सर्वोच्च शिखर सगरमाथा (८,८४८.८६ मिटर) अवस्थित छ।" },
    { en: "Nepal has the only non-quadrilateral national flag in the entire world, consisting of two triangular pennants.", ne: "नेपालको राष्ट्रिय झण्डा विश्वकै एक मात्र चारकुने नभएको त्रिकोणात्मक झण्डा हो।" },
    { en: "Lumbini in Nepal is the sacred birthplace of Lord Gautam Buddha, the Light of Asia.", ne: "नेपालको लुम्बिनी एसियाका ज्योति भगवान गौतम बुद्धको पवित्र जन्मस्थल हो।" },
    { en: "Nepal hosts over 850 bird species, representing nearly 9% of the world's total bird population.", ne: "नेपालमा ८५० भन्दा बढी प्रजातिका चराहरू पाइन्छन्, जुन विश्वको चराहरूको करिब ९% हो।" },
    { en: "Muktinath temple at 3,710m is sacred to both Hindus and Buddhists as a place of spiritual liberation.", ne: "३,७१० मिटरको उचाइमा रहेको मुक्तिनाथ मन्दिर हिन्दु र बौद्ध दुवै धर्मावलम्बीको साझा तीर्थस्थल हो।" },
  ];

  for (let i = 0; i < GRADE_BANDS.length; i++) {
    const band = GRADE_BANDS[i];
    if (existingBands.has(band)) continue;

    const gk = gkPool[i % gkPool.length];
    const np = nepalPool[i % nepalPool.length];

    const headlineEn = band === "1-5"
      ? "Explorer Day: Discover Super Wonders!"
      : band === "6-8"
      ? "Trailblazer Quest: Science & Himalayan Wonders!"
      : "Scholar Focus: SEE Prep & Global Mastery!";

    const headlineNe = band === "1-5"
      ? "अन्वेषक दिन: अद्भुत रहस्यहरू पत्ता लगाउनुहोस्!"
      : band === "6-8"
      ? "दैनिक खोज: विज्ञान र हिमाली आश्चर्यहरू!"
      : "विद्यार्थी प्रेरणा: उच्च सफलताको दैनिक यात्रा!";

    const info = db.prepare(`
      INSERT INTO digests (date, grade_band, headline_en, headline_ne, gk_fact_en, gk_fact_ne, nepal_fact_en, nepal_fact_ne, status)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'published')
    `).run(dateStr, band, headlineEn, headlineNe, gk.en, gk.ne, np.en, np.ne);

    const row = db.prepare("SELECT * FROM digests WHERE id = ?").get(info.lastInsertRowid);
    created.push(row);
  }

  return created;
}

/**
 * Executes the 7:00 AM daily digest routine.
 */
export async function executeScheduledDailyPush() {
  const local = getLocalTime();
  console.log(`[Scheduler] ⏰ Triggering 7:00 AM daily digest push for ${local.isoDate} (${local.formatted})...`);

  // Check published digests for today
  let digests = db.prepare("SELECT * FROM digests WHERE date = ? AND status = 'published'").all(local.isoDate);

  // If no published digests, check for drafts and auto-publish them
  if (!digests.length) {
    const drafts = db.prepare("SELECT * FROM digests WHERE date = ? AND status = 'draft'").all(local.isoDate);
    if (drafts.length) {
      db.prepare("UPDATE digests SET status = 'published' WHERE date = ? AND status = 'draft'").run(local.isoDate);
      digests = db.prepare("SELECT * FROM digests WHERE date = ? AND status = 'published'").all(local.isoDate);
    }
  }

  // If still no digests, auto-generate them
  if (!digests.length) {
    console.log(`[Scheduler] No digests found for today. Auto-generating fresh digests for ${local.isoDate}...`);
    digests = autoGenerateDigestsForDate(local.isoDate);
  }

  // Push notifications for each grade band
  let totalPushed = 0;
  for (const digest of digests) {
    try {
      const res = await pushDigestNotification({
        digest,
        isManual: false,
        adminEmail: "auto_scheduler@quizquest",
      });
      totalPushed += res.success;
      console.log(`[Scheduler] Published & pushed digest #${digest.id} (Grades ${digest.grade_band}): ${res.success} devices.`);
    } catch (err) {
      console.error(`[Scheduler] Error pushing digest #${digest.id}:`, err);
    }
  }

  lastRunDate = local.isoDate;
  return { date: local.isoDate, totalPushed, count: digests.length };
}

/**
 * Periodic tick checking once per minute.
 */
function tick() {
  try {
    const local = getLocalTime();
    if (
      local.hour === SCHEDULE_HOUR &&
      local.minute === SCHEDULE_MINUTE &&
      lastRunDate !== local.isoDate
    ) {
      executeScheduledDailyPush();
    }
  } catch (err) {
    console.error("[Scheduler] Tick error:", err);
  }
}

/**
 * Starts the background scheduler service.
 */
export function startDigestScheduler() {
  if (timerId) clearInterval(timerId);
  console.log(`[Scheduler] 🚀 Daily Digest Scheduler active. Configured for ${String(SCHEDULE_HOUR).padStart(2, "0")}:${String(SCHEDULE_MINUTE).padStart(2, "0")} ${TIMEZONE}.`);
  // Tick immediately and then every 30 seconds
  tick();
  timerId = setInterval(tick, 30000);
}

/**
 * Returns diagnostic details about the scheduler.
 */
export function getSchedulerStatus() {
  const local = getLocalTime();
  const tokenCount = db.prepare("SELECT COUNT(*) c FROM push_tokens").get()?.c || 0;
  const userTokensCount = db.prepare("SELECT COUNT(DISTINCT user_id) c FROM push_tokens").get()?.c || 0;
  const todayDigests = db.prepare("SELECT COUNT(*) c FROM digests WHERE date = ?").get(local.isoDate)?.c || 0;

  return {
    active: true,
    timezone: TIMEZONE,
    scheduleHour: SCHEDULE_HOUR,
    scheduleMinute: SCHEDULE_MINUTE,
    currentTime: local.formatted,
    currentDate: local.isoDate,
    lastRunDate,
    registeredTokens: tokenCount,
    uniqueUsersWithPush: userTokensCount,
    todayDigestsCount: todayDigests,
    nextRun: `${local.isoDate} ${String(SCHEDULE_HOUR).padStart(2, "0")}:${String(SCHEDULE_MINUTE).padStart(2, "0")}:00 (${TIMEZONE})`,
  };
}
